create table member (
	id VARCHAR2(50),
	pw varchar2(4),
	name VARCHAR2(100),
	phone CHAR(13),
	email VARCHAR2(50),
	gender VARCHAR2(50),
	hobby varchar2(100)
);
insert into member (id, pw, name, phone, email, gender, hobby) values ('aaa', '1111', '홍길동', '527-250-1397', 'scourtman0@dion.ne.jp', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('bbb', '1111', '유관순', '464-698-2424', 'ltalmadge1@dmoz.org', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('ccc', '1111', '이순신', '732-250-3907', 'mrudman2@google.de', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('ddd', '1111', '강감찬', '455-174-5334', 'cfarlham3@msn.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('eee', '1111', '김구', '458-294-4527', 'cblythe4@java.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('fff', '1111', '김유신', '151-966-6939', 'jszymanek5@purevolume.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('ggg', '1111', '홍길순', '326-398-0593', 'sansell6@china.com.cn', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('hhh', '1111', '홍길자', '786-945-7245', 'vgibbin7@upenn.edu', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('iii', '1111', '관순스', '584-239-6651', 'cstenton8@utexas.edu', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('jjj', '1111', '순신스', '535-344-5994', 'fphilipard9@wunderground.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('kkk', '1111', '감찬스', '644-171-1968', 'rwhitehaira@issuu.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Barnewille', '1111', 'Lucine', '704-602-1273', 'lbarnewilleb@networksolutions.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Alflatt', '1111', 'Gregoire', '470-817-1993', 'galflattc@fda.gov', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Christofor', '1111', 'Connie', '466-719-4839', 'cchristoford@meetup.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Jura', '1111', 'Diana', '154-148-7078', 'djurae@buzzfeed.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Melmeth', '1111', 'Alphonse', '811-152-1582', 'amelmethf@psu.edu', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Booton', '1111', 'Niall', '692-100-0794', 'nbootong@ehow.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Banbrick', '1111', 'Natasha', '394-106-0369', 'nbanbrickh@surveymonkey.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Lankford', '1111', 'Ethelin', '382-623-9853', 'elankfordi@canalblog.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Showalter', '1111', 'Elisabetta', '277-470-2640', 'eshowalterj@macromedia.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('De La Coste', '1111', 'Randie', '295-985-0650', 'rdelacostek@fotki.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Rous', '1111', 'Francisco', '339-721-0899', 'frousl@omniture.com', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Lenthall', '1111', 'Gaelan', '897-984-7916', 'glenthallm@wp.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Franke', '1111', 'Lauryn', '865-535-1689', 'lfranken@last.fm', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Stockbridge', '1111', 'Brinn', '989-610-6322', 'bstockbridgeo@independent.co.uk', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Hollindale', '1111', 'Rourke', '566-532-2815', 'rhollindalep@netscape.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Phelipeaux', '1111', 'Patrizia', '244-855-4793', 'pphelipeauxq@yolasite.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Stemson', '1111', 'Spense', '608-568-3646', 'sstemsonr@miibeian.gov.cn', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Keymar', '1111', 'Kris', '157-427-1011', 'kkeymars@drupal.org', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Sherston', '1111', 'Everett', '322-625-5779', 'esherstont@nhs.uk', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Sich', '1111', 'Claudine', '194-334-2189', 'csichu@domainmarket.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Tubritt', '1111', 'Farlee', '807-884-9633', 'ftubrittv@twitpic.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Janecek', '1111', 'Krisha', '779-416-6908', 'kjanecekw@goo.gl', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Comrie', '1111', 'Rog', '766-388-5018', 'rcomriex@diigo.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Ings', '1111', 'Magnum', '181-270-8173', 'mingsy@oracle.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Craig', '1111', 'Dolores', '173-229-0127', 'dcraigz@cnet.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Antonovic', '1111', 'Oralie', '831-488-2460', 'oantonovic10@indiegogo.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Baake', '1111', 'Arman', '249-634-1188', 'abaake11@jalbum.net', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Tendahl', '1111', 'Roxana', '906-907-2794', 'rtendahl12@marriott.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Tivnan', '1111', 'Bail', '345-391-4878', 'btivnan13@themeforest.net', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Pideon', '1111', 'Dorice', '361-878-6398', 'dpideon14@msn.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Lissaman', '1111', 'Templeton', '566-139-5253', 'tlissaman15@businesswire.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Brashier', '1111', 'Isidoro', '413-427-7127', 'ibrashier16@dmoz.org', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Di Giacomettino', '1111', 'Abigale', '258-724-6027', 'adigiacomettino17@networksolutions.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Duerden', '1111', 'Kurt', '296-272-4836', 'kduerden18@uol.com.br', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Bendel', '1111', 'Portie', '439-362-1630', 'pbendel19@google.it', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Battams', '1111', 'Wandie', '852-913-3363', 'wbattams1a@npr.org', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Redihalgh', '1111', 'Ryan', '711-912-9665', 'rredihalgh1b@sciencedirect.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Garnam', '1111', 'Vivyan', '582-433-4246', 'vgarnam1c@alexa.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Thomerson', '1111', 'Alexina', '684-246-3396', 'athomerson1d@reference.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Akrigg', '1111', 'Jamey', '610-234-4562', 'jakrigg1e@msn.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Aitkenhead', '1111', 'Hunter', '553-749-3805', 'haitkenhead1f@opera.com', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Tremblot', '1111', 'Faye', '424-969-7848', 'ftremblot1g@opera.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Heaney`', '1111', 'Weider', '242-747-0906', 'wheaney1h@washingtonpost.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Hugli', '1111', 'Marlyn', '208-211-1744', 'mhugli1i@icio.us', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Guyver', '1111', 'Daune', '860-751-2583', 'dguyver1j@vistaprint.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Duchart', '1111', 'Dallas', '925-312-2096', 'dduchart1k@github.com', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Lidierth', '1111', 'Roshelle', '352-867-1641', 'rlidierth1l@barnesandnoble.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Oldroyde', '1111', 'Gert', '401-688-0461', 'goldroyde1m@facebook.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Coyne', '1111', 'Nestor', '707-931-1487', 'ncoyne1n@xing.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Little', '1111', 'Carlota', '577-946-2995', 'clittle1o@skyrock.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Legan', '1111', 'Carmine', '575-551-6397', 'clegan1p@army.mil', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Dyshart', '1111', 'Arlana', '660-779-0504', 'adyshart1q@trellian.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Grazier', '1111', 'Sheryl', '696-881-6623', 'sgrazier1r@geocities.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Blewitt', '1111', 'Amye', '756-315-3374', 'ablewitt1s@cbslocal.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Beves', '1111', 'Morgan', '539-181-3243', 'mbeves1t@psu.edu', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Gilham', '1111', 'Had', '635-429-2110', 'hgilham1u@wisc.edu', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Soughton', '1111', 'Roley', '695-148-6404', 'rsoughton1v@oaic.gov.au', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Dowell', '1111', 'Caressa', '571-288-8449', 'cdowell1w@addthis.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Eads', '1111', 'Kurt', '926-419-4261', 'keads1x@fc2.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Arnholtz', '1111', 'Jodee', '925-115-1229', 'jarnholtz1y@yellowbook.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Caltun', '1111', 'Aleta', '811-760-9300', 'acaltun1z@japanpost.jp', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Matteoni', '1111', 'Maximo', '586-789-1710', 'mmatteoni20@usgs.gov', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Botler', '1111', 'Niko', '210-996-2292', 'nbotler21@furl.net', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Matuschek', '1111', 'Virgie', '419-923-5700', 'vmatuschek22@weebly.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Pardey', '1111', 'Redford', '519-534-4942', 'rpardey23@cbc.ca', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Pengilley', '1111', 'Rosamund', '462-688-6258', 'rpengilley24@liveinternet.ru', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Robinet', '1111', 'Dane', '253-638-7169', 'drobinet25@gmpg.org', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Melby', '1111', 'Padget', '167-552-6132', 'pmelby26@bbc.co.uk', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Hixley', '1111', 'Rowena', '616-252-8125', 'rhixley27@ning.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Eberle', '1111', 'Hilary', '938-855-1003', 'heberle28@nydailynews.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Milbourne', '1111', 'Northrup', '110-399-4422', 'nmilbourne29@surveymonkey.com', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Auchterlony', '1111', 'Yvon', '770-601-0501', 'yauchterlony2a@smugmug.com', 'M', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Thonason', '1111', 'Veronica', '861-537-5625', 'vthonason2b@dion.ne.jp', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Petris', '1111', 'Roderich', '984-241-0460', 'rpetris2c@elpais.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Wilsee', '1111', 'Roxanna', '939-666-4977', 'rwilsee2d@admin.ch', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Broadfield', '1111', 'Cherin', '594-427-1320', 'cbroadfield2e@yellowpages.com', 'F', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Ridgley', '1111', 'Jermaine', '586-423-7229', 'jridgley2f@wsj.com', 'M', '골프');
insert into member (id, pw, name, phone, email, gender, hobby) values ('McCreery', '1111', 'Kelly', '706-462-4747', 'kmccreery2g@google.co.jp', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Swyer-Sexey', '1111', 'Lynnette', '312-651-9792', 'lswyersexey2h@huffingtonpost.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Easterfield', '1111', 'Ellerey', '297-728-3581', 'eeasterfield2i@ibm.com', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Wadley', '1111', 'Kyla', '357-853-6076', 'kwadley2j@upenn.edu', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Slad', '1111', 'Kingston', '793-861-7193', 'kslad2k@51.la', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Jiru', '1111', 'Stormy', '646-149-1655', 'sjiru2l@list-manage.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Matsell', '1111', 'Lesly', '937-557-3187', 'lmatsell2m@va.gov', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Hanbury-Brown', '1111', 'Vivian', '616-317-0290', 'vhanburybrown2n@jimdo.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Nayer', '1111', 'Myrna', '844-977-1315', 'mnayer2o@samsung.com', 'F', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Liversidge', '1111', 'Olwen', '625-502-3708', 'oliversidge2p@purevolume.com', 'F', '조깅');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Crunden', '1111', 'Benedicto', '636-946-0937', 'bcrunden2q@miibeian.gov.cn', 'M', '게임');
insert into member (id, pw, name, phone, email, gender, hobby) values ('Eastham', '1111', 'Dillie', '151-519-9374', 'deastham2r@mtv.com', 'M', '조깅');
